import React from 'react'
import ReactDOM from 'react-dom'

var WebHookURL = React.createClass({
    propTypes: {
      baseUrl: React.PropTypes.string.isRequired,
      instanceId: React.PropTypes.string.isRequired,
      appId: React.PropTypes.string,
      configurationId: React.PropTypes.string.isRequired
    },
    getDefaultProps: function() {
      return {
        baseUrl: window.location.protocol + "//" + window.location.hostname + ":" + window.location.port
      };
    },
    getInitialState: function() {
      return {
        url: this.props.baseUrl,
        disabled: true
      };
    },
    copyURL: function(e) {
      var target = e.target;
      var copyTarget = target.dataset.copytarget;
      var textfield = (copyTarget ? document.querySelector(copyTarget) : null);
      // is element selectable?
      if (textfield && textfield.select) {
        this.setState({disabled: false});
        textfield.select();
      try {
          // copy text
          document.execCommand('copy');
          textfield.blur();
          e.target.innerHTML = "Copied!";
          setTimeout(function(){
            e.target.innerHTML = "Copy URL";
          },2000);
        } catch (err) {
          console.log(err);
        }
        this.setState({disabled: true});
      } else {
        console.log('element not found ' + copyTarget);
      }
    },
    componentWillMount: function() {
      var _url = this.props.baseUrl +"/v1/whi/"+ this.props.appId +"/"+ this.props.configurationId + '/' + this.props.instanceId;
      this.setState({
        url: _url
      })
    },
    componentDidMount: function() {
      var copyLink = document.getElementById('copy-link');
      copyLink.addEventListener('click', this.copyURL, true);
    },
    render: function() {
   	  return (
        <div className='webhook-url-container'>
          <h5>Webhook URL</h5>
          <div className="webhook-url-div">
            <input id="input-webhook-url" className="input-text ipt-whurl" type="text" value={this.state.url} placeholder="Autogenerated URL" disabled={this.state.disabled} />
            <a id="copy-link" data-copytarget="#input-webhook-url" href="javascript:void(null)">Copy URL</a>
          </div>
        </div>
      )
    }
});
module.exports = WebHookURL;
